name: atalaia_ar_condicionados_flutter_application
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter_signin_button: ^2.0.0
  flutter:
    sdk: flutter

  # --- DEPENDÊNCIAS DO PROJETO ORIGINAL ---
  url_launcher: ^6.2.6
  http: ^1.2.1
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^6.0.0
  shared_preferences: ^2.2.3
  intl: ^0.19.0

  # --- DEPENDÊNCIAS IMPORTADAS DO PROJETO FOTO ---
  provider: ^6.1.5+1  
  image_picker: ^1.2.0
  path_provider: ^2.1.5
  path: ^1.9.1
  location: ^5.0.3
  share_plus: 12.0.1

  table_calendar: ^3.1.0 # Adicione esta linha ou a versão mais recente
  geolocator: ^12.0.0 # Opcional, para pegar a localização (Lat/Lon) do usuário

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1" # Adicione esta linha (verifique a versão mais recente)

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    # - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png" # Crie este arquivo em seu projeto
  # Para Android 12 e superior (Ícones Adaptativos):
  min_sdk_android: 21 # Defina o SDK mínimo (21 é Android 5.0)
  adaptive_icon_background: "#000000" # Cor de fundo do ícone adaptativo
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png" # Parte da frente
# flutter pub run flutter_launcher_icons

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

# flutter pub get